/**
 * Database Seed Script
 * 
 * Populates the database with sample data for development and demo purposes.
 * This script creates sample companies, leads, templates, and scoring profiles.
 * It checks for existing data to prevent duplicate creation errors.
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting database seed...')

  // Check if data already exists
  const existingCompanies = await prisma.company.count()
  if (existingCompanies > 0) {
    console.log('📊 Database already contains data, skipping main seed...')
  } else {
    // Create sample companies
    const companies = await Promise.all([
      prisma.company.create({
        data: {
          name: 'TechCorp Solutions',
          domain: 'techcorp.com',
          size: 250,
          industry: 'SaaS'
        }
      }),
      prisma.company.create({
        data: {
          name: 'DataFlow Analytics',
          domain: 'dataflow.io',
          size: 120,
          industry: 'Data Analytics'
        }
      }),
      prisma.company.create({
        data: {
          name: 'CloudScale Systems',
          domain: 'cloudscale.net',
          size: 500,
          industry: 'Cloud Infrastructure'
        }
      }),
      prisma.company.create({
        data: {
          name: 'GrowthFirst Marketing',
          domain: 'growthfirst.com',
          size: 75,
          industry: 'Digital Marketing'
        }
      }),
      prisma.company.create({
        data: {
          name: 'SecureNet Security',
          domain: 'securenet.com',
          size: 180,
          industry: 'Cybersecurity'
        }
      })
    ])

    console.log(`✅ Created ${companies.length} companies`)

    // Create one sample lead without AI score (will be scored automatically)
    const leads = await Promise.all([
      prisma.lead.create({
        data: {
          companyId: companies[0].id,
          fullName: 'John Smith',
          title: 'VP of Sales',
          email: 'john.smith@techcorp.com',
          linkedinUrl: 'https://linkedin.com/in/johnsmith',
          source: 'outbound',
          score: 0, // No pre-set score - will be scored by Grok AI
          scoreBreakdown: null, // No pre-set breakdown - will be generated by AI
          stage: 'NEW',
          notes: 'Interested in improving sales efficiency with automation tools'
        }
      })
    ])

    console.log(`✅ Created ${leads.length} leads`)

    // Create sample message templates
    const templates = await Promise.all([
      prisma.messageTemplate.create({
        data: {
          name: 'Cold Outreach - VP Sales',
          body: 'Hi {{firstName}},\n\nI noticed {{companyName}} is growing rapidly in the {{industry}} space. Many companies like yours are struggling with {{painPoint}}.\n\nOur solution has helped similar companies achieve {{valueProp}}.\n\nWould you be interested in a 15-minute chat to explore if this could work for {{companyName}}?\n\nBest regards,\n{{senderName}}'
        }
      }),
      prisma.messageTemplate.create({
        data: {
          name: 'Follow-up - No Response',
          body: 'Hi {{firstName}},\n\nI wanted to follow up on my previous email about {{valueProp}} for {{companyName}}.\n\nI understand you\'re busy, so I\'ll keep this brief. Would a 10-minute call work better for you?\n\nIf not, just let me know and I\'ll remove you from our list.\n\nThanks,\n{{senderName}}'
        }
      }),
      prisma.messageTemplate.create({
        data: {
          name: 'Meeting Confirmation',
          body: 'Hi {{firstName}},\n\nGreat! I\'m looking forward to our {{meetingType}} on {{meetingDate}} at {{meetingTime}}.\n\nWe\'ll discuss how {{companyName}} can achieve {{valueProp}} and address your {{painPoint}} challenges.\n\nI\'ll send a calendar invite shortly. Let me know if you need to reschedule.\n\nBest regards,\n{{senderName}}'
        }
      })
    ])

    console.log(`✅ Created ${templates.length} message templates`)

    // Create sample scoring profiles
    const scoringProfiles = await Promise.all([
      prisma.scoringProfile.create({
        data: {
          name: 'High-Growth SaaS',
          weights: {
            industryFit: 0.3,
            sizeFit: 0.2,
            titleFit: 0.3,
            techSignals: 0.2
          },
          rules: {
            mustHave: ['domain', 'title includes VP/Head/CTO'],
            preferred: ['industry in SaaS/Data/Cloud', 'size 50-2000']
          }
        }
      }),
      prisma.scoringProfile.create({
        data: {
          name: 'Enterprise Focus',
          weights: {
            industryFit: 0.25,
            sizeFit: 0.4,
            titleFit: 0.25,
            techSignals: 0.1
          },
          rules: {
            mustHave: ['size > 500', 'title includes C-level/VP'],
            preferred: ['industry in Tech/Finance/Healthcare']
          }
        }
      })
    ])

    console.log(`✅ Created ${scoringProfiles.length} scoring profiles`)

    // Create one sample interaction for the single lead
    const interactions = await Promise.all([
      prisma.interaction.create({
        data: {
          leadId: leads[0].id,
          type: 'lead_created',
          payload: { source: 'manual_entry', timestamp: new Date().toISOString() }
        }
      })
    ])

    console.log(`✅ Created ${interactions.length} interactions`)

    // Create one sample message for the single lead
    const messages = await Promise.all([
      prisma.message.create({
        data: {
          leadId: leads[0].id,
          direction: 'outbound',
          channel: 'email',
          subject: 'Introduction to SDR Automation',
          body: 'Hi John,\n\nI noticed TechCorp Solutions is growing rapidly in the SaaS space...',
          status: 'draft',
          meta: { templateId: templates[0].id }
        }
      })
    ])

    console.log(`✅ Created ${messages.length} messages`)
  }

  // Always run evaluation seed (it has its own duplicate checking)
  console.log('🌱 Seeding evaluation test cases...')
  try {
    await seedEvalCases()
  } catch (error) {
    console.error('❌ Error seeding evaluation cases:', error)
  }

  console.log('🎉 Database seeding completed successfully!')
}

// Import and run evaluation seed function
async function seedEvalCases() {
  try {
    // Check if evaluation cases already exist
    const existingCases = await prisma.evalCase.count()
    if (existingCases > 0) {
      console.log('📊 Evaluation cases already exist, skipping seed...')
      return
    }

    // Create sample evaluation test cases
    const testCases = [
      {
        name: 'Lead Scoring - SaaS VP Sales',
        description: 'Test lead scoring for a SaaS company VP of Sales',
        category: 'scoring' as const,
        input: {
          fullName: 'John Smith',
          title: 'VP of Sales',
          company: {
            name: 'TechCorp Solutions',
            industry: 'SaaS',
            size: 250,
            domain: 'techcorp.com'
          },
          source: 'outbound',
          notes: 'Interested in improving sales efficiency'
        },
        expectedOutput: {
          score: { type: 'number', min: 1, max: 10 }, // Changed from 70-100 to 1-10 scale
          factors: { type: 'object' }, // Just check if factors exist, don't require specific keys
          rationale: { type: 'string', minLength: 10 } // Reduced from 20 to 10
        },
        criteria: [
          {
            name: 'response_quality',
            description: 'Overall response quality and relevance',
            weight: 0.25,
            validator: 'llm_judge' as const
          },
          {
            name: 'format_compliance',
            description: 'Response follows expected format',
            weight: 0.25,
            validator: 'custom' as const
          },
          {
            name: 'completeness',
            description: 'Response contains all required elements',
            weight: 0.25,
            validator: 'contains' as const
          },
          {
            name: 'accuracy',
            description: 'Response is accurate and logical',
            weight: 0.25,
            validator: 'llm_judge' as const
          }
        ],
        metadata: {
          difficulty: 'easy', // Changed from medium to easy
          expectedDuration: 5000,
          tags: ['saas', 'vp-sales', 'high-fit']
        }
      },
      {
        name: 'Outreach Generation - Follow-up',
        description: 'Test outreach message generation for follow-up scenario',
        category: 'outreach' as const,
        input: {
          leadId: 'sample-lead-123',
          templateId: 'follow-up-template',
          context: 'Previous conversation about sales automation'
        },
        expectedOutput: {
          subject: { type: 'string', minLength: 3 }, // Reduced from 5 to 3
          body: { type: 'string', minLength: 20 }, // Reduced from 50 to 20
          safety: { type: 'object' } // Just check if safety exists
        },
        criteria: [
          {
            name: 'response_quality',
            description: 'Overall response quality and relevance',
            weight: 0.25,
            validator: 'llm_judge' as const
          },
          {
            name: 'format_compliance',
            description: 'Response follows expected format',
            weight: 0.25,
            validator: 'custom' as const
          },
          {
            name: 'completeness',
            description: 'Response contains all required elements',
            weight: 0.25,
            validator: 'contains' as const
          },
          {
            name: 'accuracy',
            description: 'Response is accurate and logical',
            weight: 0.25,
            validator: 'llm_judge' as const
          }
        ],
        metadata: {
          difficulty: 'easy',
          expectedDuration: 3000,
          tags: ['follow-up', 'professional', 'safety']
        }
      },
      {
        name: 'General AI - Hello World',
        description: 'Basic AI response test',
        category: 'general' as const,
        input: {
          prompt: 'Say hello world in a friendly way'
        },
        expectedOutput: {
          response: { type: 'string', contains: 'hello' }
        },
        criteria: [
          {
            name: 'response_quality',
            description: 'Overall response quality and relevance',
            weight: 0.25,
            validator: 'llm_judge' as const
          },
          {
            name: 'format_compliance',
            description: 'Response follows expected format',
            weight: 0.25,
            validator: 'custom' as const
          },
          {
            name: 'completeness',
            description: 'Response contains all required elements',
            weight: 0.25,
            validator: 'contains' as const
          },
          {
            name: 'accuracy',
            description: 'Response is accurate and logical',
            weight: 0.25,
            validator: 'llm_judge' as const
          }
        ],
        metadata: {
          difficulty: 'easy',
          expectedDuration: 1000,
          tags: ['basic', 'hello-world', 'tone']
        }
      },
      {
        name: 'Lead Qualification - Enterprise CTO',
        description: 'Test lead qualification for enterprise CTO',
        category: 'qualification' as const,
        input: {
          fullName: 'Michael Chen',
          title: 'CTO',
          company: {
            name: 'CloudScale Systems',
            industry: 'Cloud Infrastructure',
            size: 500,
            domain: 'cloudscale.net'
          },
          source: 'outbound',
          notes: 'Exploring automation solutions'
        },
        expectedOutput: {
          qualified: { type: 'boolean' }, // Just check if boolean exists
          reasoning: { type: 'string', minLength: 10 }, // Reduced from 30 to 10
          confidence: { type: 'number' } // Just check if number exists
        },
        criteria: [
          {
            name: 'qualification_decision',
            description: 'Should make a qualification decision',
            weight: 0.4,
            validator: 'contains' as const
          },
          {
            name: 'confidence_score',
            description: 'Should provide confidence level',
            weight: 0.3,
            validator: 'contains' as const
          },
          {
            name: 'reasoning_quality',
            description: 'Should provide reasonable explanation',
            weight: 0.3,
            validator: 'llm_judge' as const
          }
        ],
        metadata: {
          difficulty: 'easy', // Changed from medium to easy
          expectedDuration: 4000,
          tags: ['enterprise', 'cto', 'qualification']
        }
      }
    ]

    // Create test cases
    for (const testCase of testCases) {
      await prisma.evalCase.create({
        data: testCase
      })
    }

    console.log(`✅ Created ${testCases.length} evaluation test cases`)

  } catch (error) {
    console.error('❌ Failed to seed evaluation test cases:', error)
    throw error
  }
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
